# Generated by Django 2.2 on 2019-04-29 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=50)),
                ('finalGrade', models.CharField(max_length=5)),
                ('graduated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('permission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('classroom', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('collaborators', models.ManyToManyField(to='appbackend.Person')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Course')),
                ('enrollments', models.ManyToManyField(to='appbackend.Enrolled')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='appbackend.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Person')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Turma'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appbackend.Person'),
        ),
    ]
