# Generated by Django 2.2 on 2019-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='finalGrade',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
