# Generated by Django 2.2 on 2019-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0002_auto_20190429_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='enrollments',
            field=models.ManyToManyField(blank=True, to='appbackend.Enrolled'),
        ),
    ]
